apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    resources:
      limits:
        memory: "64Mi" #64 MB
        cpu: "50m" #50 millicpu (.05 cpu or 5% of the cpu)
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:                 # Aqui sé o container não funcionar vamos executar o comando
        - cat                    # vamos mostrar o que tem no arquivo healthy
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/