apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi" #128 MB
        cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)
    ports:
    - containerPort: 80
    livenessProbe:                # temos um liveness prob
      httpGet:                    # Aqui vamos dá um Https get
        path: /index.html         # Na pagina index na porta 80
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2 # Default is 1
      periodSeconds: 5 # Default is 10
      failureThreshold: 1 # Default is 3
    readinessProbe:               # Aqui tambem temos o liveness probre que praticamente faz a mesma coisa
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5 # Default is 10
      failureThreshold: 1 # Default is 3

# Aplicando
#   > kubectl apply -f  nginx-readiness-probe.pod.yml

# Vamos rodar o container, o nome deste container é my-nginx
# kubectl exec pod-name -c my-nginx -it /bin/sh

