apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: clone-sc
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: origin-pvc
---
kind: Pod
apiVersion: v1
metadata:
  name: clone-pod
spec:
  volumes:
    - name: clone-vol
      persistentVolumeClaim:
        claimName: clone-pvc
  containers:
    - name: clone-ctr
      image: ubuntu
      command:
      - /bin/bash
      - "-c"
      - "sleep 60m"
      volumeMounts:
      - mountPath: /data
        name: clone-vol
