apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  volumes:
    - name: fast50g
      persistentVolumeClaim:
        claimName: ps-pvc
  containers:
  - image: ubuntu:latest
    name: ctr1
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    volumeMounts: 
    - mountPath: /data
      name: fast50g
