apiVersion: v1 
kind: Pod 
metadata:
  name: docker-volume
spec: 
  containers: 
  - name: docker   # O container tem o nome de docker, nada mais q isso
    image: docker 
    command: ["sleep"] 
    args: ["100000"]
    volumeMounts: 
    - name: docker-socket 
      mountPath: /var/run/docker.sock # Este é o ponto de montagem, que vai falar com host 
    resources:
  volumes: 
  - name: docker-socket 
    hostPath:
      path: /var/run/docker.sock   # Aqui é a indicação do path no host para linkar com o volume
      type: Socket

# Once Pod is created you can shell into it to run Docker commands:
# kubectl exec [pod-name] -it sh
